# Generated by Django 3.1.6 on 2021-02-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('contents', models.TextField()),
                ('authors', models.TextField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
